bashrc: Ensure input matches pattern in ',syncthing-conflict-diff'

diff --git a/dotfiles/bashrc/bashrc b/dotfiles/bashrc/bashrc
--- a/dotfiles/bashrc/bashrc
+++ b/dotfiles/bashrc/bashrc
@@ -449,7 +449,12 @@ _assert_cmd() {
         echo "Usage: ${FUNCNAME[0]} FILE.sync-conflict-XXXXX.txt" 1>&2
         return 1
     fi
+
     input="$1"
+    if [[ $input != *.sync-conflict-+([0-9])-+([0-9])-+([^.])* ]]; then
+        echo "${FUNCNAME[0]}: Input file '$input' does not match expected conflict pattern. Aborting." 1>&2
+        return 1
+    fi
     if [ ! -e "$input" ]; then
         echo "${FUNCNAME[0]}: Input file '$input' does not exist. Aborting." 1>&2
         return 1
