Change error messages for gcco and add exit codes

diff --git a/dotfiles/bashrc/gcco b/dotfiles/bashrc/gcco
--- a/dotfiles/bashrc/gcco
+++ b/dotfiles/bashrc/gcco
@@ -6,6 +6,7 @@ EXECUTE=false
 
 if [[ -f $1 ]]; then
     out_file="$(echo $1 | cut -d '.' -f 1).out"
+
     if [[ -f $out_file ]]; then
         rm $out_file
     fi
@@ -17,11 +18,13 @@ if [[ -f $1 ]]; then
             echo "[gcco] Done. Running..."
             ./$filename
         else
-            echo "[gcco] Error. Aborted."
+            echo "[gcco] Error. Can't find the binary when trying to run."
+            exit 1;
         fi
     else
         echo "[gcco] Done. Compiled as $out_file"
     fi
 else
-    echo "[gcco] Error. No such file."
+    echo "[gcco] Error. No such file."      # Could not find user input
+    exit 1;
 fi
