Add virt-manager.sh, remove gcco, improve nasmo

diff --git a/scripts/usr/misc/nasmo b/scripts/usr/misc/nasmo
--- a/scripts/usr/misc/nasmo
+++ b/scripts/usr/misc/nasmo
@@ -1,48 +1,35 @@
 #!/bin/bash
 
-#--------- SETTINGS ---------
-EXECUTE=false               # Execute after compilation
-RM_OBJ=true                 # Remove object file after linking
-NASM_OPTS="-f elf"          # Compiler
-LD_OPTS="-m elf_i386"       # Linker
-#----------------------------
+RM_OBJ=true           # Remove object file after linking
+ASFLAGS="-f elf"      # Assembler
+LDFLAGS="-m elf_i386" # Linker
 
-if [[ -f $1 ]]; then
-    obj_file="$(echo $1 | cut -d '.' -f 1).o"
-    out_file="${obj_file}ut"                    # *.o -> *.out
-    
-    if [[ -f $obj_file ]]; then
-        rm $obj_file
-    fi
-    if [[ -f $out_file ]]; then
-        rm $out_file
-    fi
+#-------------------------------------------------------------------------------
 
-    nasm $NASM_OPTS $1
-
-    if ! [[ -f $obj_file ]]; then        # Object file does not exist
-        echo "[nasmo] Error. Can't find the object file after compilation."
-        exit 1;
-    fi
-
-    ld $LD_OPTS -o $out_file $obj_file
-
-    if [[ $RM_OBJ == true ]]; then
-        rm $obj_file                    # Remove object file after linking
-    fi
-
-    if [[ $EXECUTE == true ]]; then
-        if [[ -f $out_file ]]; then
-            echo "[nasmo] Done. Running..."
-            ./$filename
-        else
-            echo "[nasmo] Error. Can't find the binary when trying to run."
-            exit 1;
-        fi
-    else
-        echo "[nasmo] Done. Compiled as $out_file"
-    fi
-else
-    echo "[nasmo] Error. No such file."      # Could not find user input
+if [[ ! -f $1 ]]; then
+    echo "[nasmo] Error. No such file."
     exit 1;
+fi
+
+obj_file="$(echo $1 | cut -d '.' -f 1).o"
+out_file="${obj_file}ut"  # *.o -> *.out
+
+if [[ -f $obj_file ]]; then
+    rm $obj_file
+fi
+if [[ -f $out_file ]]; then
+    rm $out_file
+fi
+
+nasm $ASFLAGS $1
+
+if ! [[ -f $obj_file ]]; then
+    echo "[nasmo] Error. Can't find the object file after assembling."
+    exit 1;
+fi
+
+ld $LDFLAGS -o $out_file $obj_file
+
+if [[ $RM_OBJ == true ]]; then
+    rm $obj_file  # Remove object file after linking
 fi
